### ISSUE TITLE
Error inquery

### ISSUE THREAD

**Issue by Lungsangg** [r7kamura/google-docs-to-github#1]
Hello @r7kamura , first of all thank you for your work, google-docs-to-github seems really useful. I am facing an issue while trying to run your action. I have post the error below. Can you please have a look on what may be the issue, I have done every possible troubleshoot in google-github-actions/auth step. It would help alot, Thanks!

```
Run r7kamura/google-docs-to-markdown@v0
  with:
    google_drive_folder_id: 1oVMxR8FtWre1k2bqDOxpLYbPDUrifBv7
    output_directory_path: output
  env:
    CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /home/runner/work/Gdoc2github/Gdoc2github/gha-creds-a852ff7acf2e933b.json
    GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/Gdoc2github/Gdoc2github/gha-creds-a852ff7acf2e933b.json
    GOOGLE_GHA_CREDS_PATH: /home/runner/work/Gdoc2github/Gdoc2github/gha-creds-a852ff7acf2e933b.json
    CLOUDSDK_CORE_PROJECT: test1-395[20](https://github.com/Lungsangg/Gdoc2github/actions/runs/5782285558/job/15668815015#step:3:21)6
    CLOUDSDK_PROJECT: test1-395206
    GCLOUD_PROJECT: test1-395206
    GCP_PROJECT: test1-395206
    GOOGLE_CLOUD_PROJECT: test1-395206
Error: Error: Error code invalid_target: The target service indicated by the "audience" parameters is invalid. This might either be because the pool or provider is disabled or deleted or because it doesn't exist.
```

**Comment by r7kamura** [comment]
This is the first error I see. Maybe the value passed to google-github-actions/auth@v0 is incorrect. Specifically, is the value of `workload_identity_provider` incorrect?

It looks like you are passing the following setting:

```
workload_identity_provider: projects/562436113365/locations/global/workloadIdentityPools/github-actions-1/providers/my-provider-id
```

Since the ID of the provider is the part you are naming, `my-provider-id` seems strange to me.

**Comment by Lungsangg** [comment]
Thank you! It's a silly mistake from my side :) I have update ```my-provider-id``` and after solving some other errors, work flow seems to be running fine (or no errors) but files from my google doc is not transferring in my repo. I have shared the google drive folder with my service account in previous steps. Do you have any idea, what I might be doing wrong here? PS: sorry for the additional question

**Comment by r7kamura** [comment]
hmm, are you sure you are not putting a sub-folder within the folder? Only files directly under the directory should be covered.

**Comment by Lungsangg** [comment]
Looks like I shared wrong service account id to my Gdrive folder. Its working fine now. Thank you!
